### ISSUE TITLE
qrs detection fore large holter data

### ISSUE THREAD

**Issue by ahmadi219** [gdupret/eplimited#1]
Hello
I want to use qrs detection classification in my project. my data files are so much big ( 24 to 48 hour data)
if I run BeatDetectionAndClassification for all of points in my signal, It takes about twenty minutes or more
how can I run this function for large data ? Is there a multi thread solution for large data ? or cuda implementation to reduce time of analysis ?
Please help me for this ...
Thanks
Best Regards

**Comment by gdupret** [comment]
Hi! The short answer is that I am not aware of a parallel version. 

I am not sure this is still relevant to you, but I guess the simplest way is to divide your signal in as many cores as you have and run them in parallel in R. just make sure you have some overlapping between the ends of the signal pieces to prime the algorithm. So if you have 12 cores and 12 hours of signal, start the second piece of the signal at say 55' instead of 60', and then discard the leading 5'. This should be more than enough.
